# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            blog
tagline:          'my secret approach for conquering cancer'
description:      'Keeping my daily cancer-based life simple and incredible at the same time. Made by <a href="https://twitter.com/aaronjlee" target="_blank">@aaronjlee</a>.'
url:              http://aaronjlee.github.io/
baseurl:          /

author:
  name:           'Aaron Lee'
  url:            https://twitter.com/aaronjlee

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/aaronjlee
